linters:
  enable:
    - gocritic
    - asciicheck
    - bodyclose
    - deadcode
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - vet
    - wsl
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: line-length-limit
        severity: error
        arguments: [500]
      - name: unhandled-error
        arguments: ["fmt.printf", "myFunction"]
      - name: bare-return
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: early-return
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: errorf
      - name: exported
      - name: if-return
      - name: imports-blacklist
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unexported-return
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: deadcode
