// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
)

type User struct {
	ID          string         `json:"id"`
	FullName    sql.NullString `json:"full_name"`
	Password    sql.NullString `json:"password"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Email       sql.NullString `json:"email"`
	Role        sql.NullInt32  `json:"role"`
	Active      sql.NullBool   `json:"active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}
