// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: product_variant.sql

package sqlc

import (
	"context"
	"time"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (id, p_id, name, colour,
                             created_at, updated_at, created_by, updated_by)
VALUES (gen_random_uuid(), $1::char(36), $2::varchar, $3::varchar,
        now() at time zone 'Asia/Jakarta', now() at time zone 'Asia/Jakarta', $4::varchar, $5::varchar)
RETURNING id::char(36)
`

type CreateProductVariantParams struct {
	PID       string `json:"p_id"`
	Name      string `json:"name"`
	Colour    string `json:"colour"`
	CreatedBy string `json:"created_by"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.PID,
		arg.Name,
		arg.Colour,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteProductVariantByID = `-- name: DeleteProductVariantByID :one
DELETE
FROM product_variants
WHERE id = $1::char(36)
RETURNING id
`

func (q *Queries) DeleteProductVariantByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteProductVariantByID, id)
	err := row.Scan(&id)
	return id, err
}

const getProductVariantByID = `-- name: GetProductVariantByID :one
SELECT id:: char(36),
        p_id::char(36),
        name::varchar,
        colour::varchar,
        created_at::timestamp,
        updated_at::timestamp,
        created_by::varchar,
        updated_by::varchar
FROM product_variants
WHERE id = $1::char(36)
`

type GetProductVariantByIDRow struct {
	ID        string    `json:"id"`
	PID       string    `json:"p_id"`
	Name      string    `json:"name"`
	Colour    string    `json:"colour"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
}

func (q *Queries) GetProductVariantByID(ctx context.Context, id string) (GetProductVariantByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantByID, id)
	var i GetProductVariantByIDRow
	err := row.Scan(
		&i.ID,
		&i.PID,
		&i.Name,
		&i.Colour,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProductVariants = `-- name: GetProductVariants :many
SELECT id:: char(36),
        p_id::char(36),
        name::varchar,
        colour::varchar,
        created_at::timestamp,
        updated_at::timestamp,
        created_by::varchar,
        updated_by::varchar
FROM product_variants
`

type GetProductVariantsRow struct {
	ID        string    `json:"id"`
	PID       string    `json:"p_id"`
	Name      string    `json:"name"`
	Colour    string    `json:"colour"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
}

func (q *Queries) GetProductVariants(ctx context.Context) ([]GetProductVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductVariantsRow
	for rows.Next() {
		var i GetProductVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PID,
			&i.Name,
			&i.Colour,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariantsByProductID = `-- name: GetProductVariantsByProductID :many
SELECT id:: char(36),
        p_id::char(36),
        name::varchar,
        colour::varchar,
        created_at::timestamp,
        updated_at::timestamp,
        created_by::varchar,
        updated_by::varchar
FROM product_variants WHERE p_id = $1::char(36)
`

type GetProductVariantsByProductIDRow struct {
	ID        string    `json:"id"`
	PID       string    `json:"p_id"`
	Name      string    `json:"name"`
	Colour    string    `json:"colour"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
}

func (q *Queries) GetProductVariantsByProductID(ctx context.Context, productID string) ([]GetProductVariantsByProductIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductVariantsByProductIDRow
	for rows.Next() {
		var i GetProductVariantsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PID,
			&i.Name,
			&i.Colour,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariantByID = `-- name: UpdateProductVariantByID :one
UPDATE product_variants SET
        p_id= $1::char(36),
        name= $2::varchar,
        colour= $3::varchar,
        created_at= $4::timestamp,
        updated_at= $5::timestamp,
        created_by= $6::varchar,
        updated_by= $7::varchar
WHERE id = $8::char(36) RETURNING id::char(36), p_id::char(36), name::varchar, colour::varchar,created_at::timestamp,
    updated_at::timestamp, created_by::varchar, updated_by::varchar
`

type UpdateProductVariantByIDParams struct {
	PID       string    `json:"p_id"`
	Name      string    `json:"name"`
	Colour    string    `json:"colour"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
	ID        string    `json:"id"`
}

type UpdateProductVariantByIDRow struct {
	ID        string    `json:"id"`
	PID       string    `json:"p_id"`
	Name      string    `json:"name"`
	Colour    string    `json:"colour"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
}

func (q *Queries) UpdateProductVariantByID(ctx context.Context, arg UpdateProductVariantByIDParams) (UpdateProductVariantByIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariantByID,
		arg.PID,
		arg.Name,
		arg.Colour,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.ID,
	)
	var i UpdateProductVariantByIDRow
	err := row.Scan(
		&i.ID,
		&i.PID,
		&i.Name,
		&i.Colour,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
